import type { Metadata } from 'next';
import './globals.css';
import { hasLocale } from 'next-intl';
import { routing } from '@/i18n/routing';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) => {
  const { locale } = await params;

  const isValidLocale = hasLocale(routing.locales, locale);

  const finalLocale = isValidLocale ? locale : routing.defaultLocale;

  // if (!isValidLocale) {
  //   redirect(`/${routing.defaultLocale}`);
  // }
  return (
    <html lang={finalLocale}>
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
